version: '3'

services:
  user-backend:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/yijun/.ssh
      - ..:/opt/yijun/code
      - ~/etc/localtime:/opt/yijun/etc/localtime
      - ~/etc/timezone:/opt/yijun/etc/timezone
    command: ["tail -f /dev/null"]
    ports:
      - 8006:8000
    depends_on:
      - db
    networks:
      - my-website

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - my-website

networks:
  my-website:
    external: true




