name: ci

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  build:
    environment: my-website
    runs-on: ubuntu-latest
    steps:
    - name: trigger-my-jenkins
      env: # Or as an environment variable
        JENKINSUSERNAME: ${{ secrets.JENKINSUSERNAME }}
        JENKINSPASSWORD: ${{ secrets.JENKINSPASSWORD }}
        JENKINSDOMAIN: ${{ secrets.JENKINSDOMAIN }}
        JENKINSPIPELINETOKEN: ${{ secrets.JENKINSPIPELINETOKEN }}
        BRANCH: ${{ github.ref_name }}
      run: | 
        echo the branch is ${BRANCH} and jenkins username is ${JENKINSUSERNAME}
        curl \
        --user ${JENKINSUSERNAME}:${JENKINSPASSWORD} \
        "https://${JENKINSDOMAIN}/job/my-website-be/buildWithParameters?token=${JENKINSPIPELINETOKEN}&BRANCH=${BRANCH}"