name: ci

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  build:
    environment: my-website
    runs-on: ubuntu-latest
    steps:

    - name: trigger-my-jenkins
      env: # Or as an environment variable
        JENKINSUSERNAME: ${{ secrets.JENKINSUSERNAME }}
        JENKINSPASSWORD: ${{ secrets.JENKINSPASSWORD }}
        BRANCH: ${{ github.ref_name }}
      run: | 
        echo the branch is ${BRANCH} and jenkins username is ${JENKINSUSERNAME}
        curl  --user ${JENKINSUSERNAME}:${JENKINSPASSWORD} "https://jenkins.giraffoxy.info/job/my-website-be/buildWithParameters?token=lalalahjahaha&BRANCH=${BRANCH}"