name: ci

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: just-a-test
      run: | 
        echo the branch is ${{ github.ref_name }}
        echo the repo is ${{ github.repository }}
    # - name: Triger jenkins
    #   run: |
    #     curl  -X POST "https://<JENKINS_URL>/buildByToken/buildWithParameters?" \
    #           --data "token=<AUTHENTICATION_TOKEN>" \
    #           --data "job=<JOB_NAME>" \
    #           --data "param_name1=param_value1"
    #           --data "param_name2=param_value2"